## python_tests.yml
## Evan Garvey
## IS 601, Module 3

name: Python tests on Push / Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs: 
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
      - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      - name: Run tests
      - run: |
        python -m pytest --cov=app --cov-fail-under=100